name: Periodic health check

on:
  push:
    branches: 
      - main

jobs:
  ping:
    runs-on: ubuntu-20.04
    steps:
      - name: URL Health Check
        uses: Jtalk/url-health-check-action@v3.2
        with:
          url: https://pokedex246.fly.dev/ping